---
apiVersion: v1
kind: Namespace
metadata:
  name: promexporter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: promexporter
  name: deployment-promexporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-promexporter
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-promexporter
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: app-promexporter
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: promexporter
  name: service-promexporter
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: app-promexporter
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: promexporter
  name: ingress-promexporter
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: service-promexporter
              port:
                number: 80
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: alb-ingress-controller
  name: alb-ingress-controller
rules:
  - apiGroups:
      - ""
      - extensions
    resources:
      - configmaps
      - endpoints
      - events
      - ingresses
      - ingresses/status
      - services
    verbs:
      - create
      - get
      - list
      - update
      - watch
      - patch
  - apiGroups:
      - ""
      - extensions
    resources:
      - nodes
      - pods
      - secrets
      - services
      - namespaces
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: alb-ingress-controller
  name: alb-ingress-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: alb-ingress-controller
subjects:
  - kind: ServiceAccount
    name: alb-ingress-controller
    namespace: promexporter
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: alb-ingress-controller
  name: alb-ingress-controller
  namespace: promexporter
